name: Valgrind

on:
  push:
    branches: [ "main", "**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: [debug, release]
        compiler: [gcc, clang]
        include:
          - target: x86_64

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        recursive: true

    - name: Install Valgrind
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> ~/.bashrc
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        sudo apt-get update
        sudo apt-get install build-essential
        sudo apt-get install libc6-dbg
        brew install valgrind
        echo "Valgrind installed"

    - name: Build project
      run: |
        ./script/bootstrap.sh
        ./local/bam/bam config=${{ matrix.config }} platform=linux_x86_64 compiler=${{ matrix.compiler }}

    - name: Run Tests
      run: |
        ./local/bam/bam config=${{ matrix.config }} platform=linux_x86_64 compiler=${{ matrix.compiler }} test

    - name: Run Tests with Valgrind
      run: |
        set PATH=$PATH:/home/linuxbrew/.linuxbrew/bin
        ./local/bam/bam config=${{ matrix.config }} platform=linux_x86_64 compiler=${{ matrix.compiler }} test_valgrind

